# Define persistent volume resource with specified capacity
kind: PersistentVolume
apiVersion: v1
metadata:
  name: mongo-pv-volume
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 3Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data/mongo"
---
# Claim part of the PersistentVolume for volume needs
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongo-pv-claim
spec:
  storageClassName: standard
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
# MongoDB initialization script
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-initdb-config
data:
  1_setup_users.js: |
    db.createUser(
      {
        user: "devops",
        pwd: "devops",
        roles : [
          {"role" : "userAdmin", "db" : "volvox"},
          {"role" : "dbAdmin", "db" : "volvox"},
          {"role" : "readWrite", "db" : "volvox"}
        ],
        mechanisms:[
          "SCRAM-SHA-1"
        ]
      }
    );
    db.createUser(
      {
        user: "client",
        pwd: "client",
        roles : [{"role" : "readWrite", "db" : "volvox"}],
          mechanisms:[
          "SCRAM-SHA-1"
        ]
      }
    )
---
# MongoDB deployment spec
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
spec:
  selector:
    matchLabels:
      app: mongo
      role: master
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: mongo
        role: master
        tier: backend
    spec:
      containers:
      - name: mongo
        image: mongo
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            value: "admin"
          - name: MONGO_INITDB_ROOT_PASSWORD
            value: "admin"
          - name: MONGO_INITDB_DATABASE
            value: "volvox"
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: data
          mountPath: /data/db
        - name: mongo-initdb
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: mongo-pv-claim
      - name: mongo-initdb
        configMap:
          name: mongo-initdb-config
---
# MongoDB service spec
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  labels:
    app: mongo
    role: master
    tier: backend
spec:
  ports:
  - port: 27017
    targetPort: 27017
  # Replace with the IP of your minikube node / master node if you want external access
  externalIPs:
  - 192.168.99.100
  selector:
    app: mongo
    role: master
    tier: backend