apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: @projectName@-deployment
  labels:
    app: @groupName@
spec:
  replicas: 1
  selector:
    matchLabels:
      app: @projectName@
  template:
    metadata:
      labels:
        app: @projectName@
        actorSystemName: volvox
    spec:
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
      containers:
      - name: @projectName@
        image: @dockerImage@
        volumeMounts:
          - mountPath: /dev/shm
            name: dshm
        imagePullPolicy: Never
        livenessProbe:
          tcpSocket:
            port: 8558
        ports:
        # akka remoting
        - name: remoting
          containerPort: 25520
          protocol: TCP
        # akka-management bootstrap
        - name: bootstrap
          containerPort: 8558
          protocol: TCP
        # external http
        - name: akka-mgmt-http
          containerPort: 8558
          protocol: TCP
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-reader
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: read-pods
subjects:
# Note the `name` line below. The first default refers to the namespace. The second refers to the service account name.
# For instance, `name: system:serviceaccount:myns:default` would refer to the default service account in namespace `myns`
- kind: User
  name: system:serviceaccount:default:default
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
